from interp import Add, Sub, Mul, Div, Neg, Lit, Let, Name, ImageLit, ImageValue, Merge, Rotate, And, Or, Not, Eq, Lt, If, LetFun, App, run, Expr

from lark import Lark, Token, ParseTree, Transformer
from lark.exceptions import VisitError
from pathlib import Path

#parser = Lark(Path('expr.lark').read_text(),start='expr',parser='earley',ambiguity='explicit')
parser = Lark(Path('expr.lark').read_text(),start='expr',parser='lalr',strict=True)

class ParseError(Exception):
    pass

def parse(s:str) -> ParseTree:
    try:
        return parser.parse(s)
    except Exception as e:
        raise ParseError(e)

class AmbiguousParse(Exception):
    pass

class ToExpr(Transformer[Token,Expr]):
    '''Defines a transformation from a parse tree into an AST'''
    # This is structured as a "fold" over the parse tree.
    # There is a method for each named ("aliased") rule in the grammar,
    # invoked on nodes generated by that rule. 
    # The args are the _result_ of recursively 
    # applying the transformer to the children of the node
    # (we do not have to write the recursive calls explicitly).
    # For leaf nodes, the argument is a Token; the string that
    # actually makes up the token is in the .value field.
    # (We cheat by declaring the args as tuples rather than lists, since
    # this let's us be more precise about the types of the elements.)
    # Fail if tree contains ambiguity markers
    def plus(self, args:tuple[Expr,Expr]) -> Expr:
        return Add(args[0],args[1])
    def times(self, args:tuple[Expr,Expr]) -> Expr:
        return Mul(args[0],args[1])
    def minus(self, args:tuple[Expr,Expr]) -> Expr:
        return Sub(args[0],args[1])
    def divide(self, args:tuple[Expr,Expr]) -> Expr:
        return Div(args[0],args[1])
    def neg(self, args:tuple[Expr]) -> Expr:
        return Neg(args[0])
    def let_expr(self, args:tuple[Token,Expr,Expr]) -> Expr:
        return Let(args[0].value,args[1],args[2])
    def id(self, args:tuple[Token]) -> Expr:
        name = args[0].value

        if name == "true":
            return Lit(True)
        if name == "false":
            return Lit(False)
        return Name(name)

    def int_lit(self,args:tuple[Token]) -> Expr:
        return Lit(int(args[0].value))
    def string_lit(self, args) -> Expr:
        return Lit(args[0].value[1:-1])
    def if_expr(self,args:tuple[Expr,Expr,Expr]) -> Expr:
        return If(args[0],args[1],args[2])

    # ₊✩‧₊˚౨ৎ˚₊✩‧₊     IMAGE CLASS      ₊✩‧₊˚౨ৎ˚₊✩‧₊
    def img_lit(self, args) -> ImageValue:
        #        print(f"img_lit args: {args}, value: {args[0]}")
        filename = args[0].value[1:-1]
        return ImageLit(filename)
    def merge_expr(self, args) -> ImageValue:
        return Merge(args[0], args[1])
    def rotate_expr(self, args) -> ImageValue:
        return Rotate(args[0])
    
    def and_e(self, args) -> Expr:
        return And(args[0], args[1])
    def or_e(self, args) -> Expr:
        return Or(args[0], args[1])
    def not_e(self, args) -> Expr:
        return Not(args[0])
    def eq(self, args) -> Expr:
        return Eq(args[0],args[1])
    def lt(self, args) -> Expr:
        return Lt(args[0], args[1])


    def letfun_expr(self,args:tuple[Token,Token,Expr,Expr]) -> Expr:
        return LetFun(args[0].value,args[1].value,args[2],args[3])
    def app(self,args:tuple[Expr,Expr]) -> Expr:
        return App(args[0], args[1])
    def _ambig(self,_) -> Expr:    # ambiguity marker
        raise AmbiguousParse()


def genAST(t:ParseTree) -> Expr:
    '''Applies the transformer to convert a parse tree into an AST'''
    # boilerplate to catch potential ambiguity error raised by transformer
    try:
        return ToExpr().transform(t)
    except VisitError as e:
        if isinstance(e.orig_exc,AmbiguousParse):
            raise AmbiguousParse()
        else:
            raise e

def parse_and_run(s: str):
    try:
        t = parse(s)
        print("pretty:")
        print(t.pretty())
        ast = genAST(t)
        print("raw AST:", repr(ast))
        run(ast)
        print("\n₊✩‧₊˚౨ৎ˚₊✩‧₊₊✩‧₊˚౨ৎ˚₊✩‧₊₊✩‧₊˚౨ৎ˚₊✩‧₊₊✩‧₊˚౨ৎ˚₊✩‧₊\n")
    except AmbiguousParse:
        print("ambiguous parse")
    except ParseError as e:
        print("parse error:", e)

#CREDIT TO PROF YAO LI
# Thank you for providing code strcuture 
# to work off of and for guiding us through
#class so we can understand it. 


# ₊✩‧₊˚౨ৎ˚₊✩‧₊ CORE ₊✩‧₊˚౨ৎ˚₊✩‧₊
parse_and_run("1 + 2 * 3")
parse_and_run("(10 - 4) / 2")
parse_and_run("let x = 5 in x + x end")

#₊✩‧₊˚౨ৎ˚₊✩‧₊ BOOL & CMP ₊✩‧₊˚౨ৎ˚₊✩‧₊ 
parse_and_run("true || false")
parse_and_run("!false && true")
parse_and_run("3 == 3")
parse_and_run("2 < 5")
parse_and_run("if 3 < 10 then 42 else 0")

# ₊✩‧₊˚౨ৎ˚₊✩‧₊ FUNCTIONS ₊✩‧₊˚౨ৎ˚₊✩‧₊
parse_and_run("letfun double(x) = x + x in double(7) end")
parse_and_run("letfun square(n) = n * n in square(5) end")


# ₊✩‧₊˚౨ৎ˚₊✩‧₊ IMAGES ₊✩‧₊˚౨ৎ˚₊✩‧₊
parse_and_run('img("images/cutephoto.jpg")')
parse_and_run('rotate(img("images/cutephoto.jpg"))')
parse_and_run('merge(img("images/cutephoto.jpg"), img("images/cutephoto.jpg"))')
parse_and_run('let pic = img("images/cutephoto.jpg") in rotate(pic) end')
parse_and_run('letfun spin(p) = rotate(p) in spin(img("images/cutephoto.jpg")) end')
parse_and_run('letfun rot180(p) = rotate(rotate(p)) in rot180(img("images/cutephoto.jpg")) end')
parse_and_run('let a = img("images/cutephoto.jpg") in rotate(merge(a, a)) end')
parse_and_run('if true then rotate(img("images/cutephoto.jpg")) else img("images/cutephoto.jpg")')
